language: python
dist: xenial
python:
  - 3.7

jobs:
  include:
    - name: "Syntax validation"
      addons: false
      cache: false
      script:
         - python3 -m compileall -q *

    - name: "Static code analysis - Flake8"
      addons: false
      cache: false
      script:
         - .travis/run-flake8
      if: type = pull_request
