#!/bin/sh -ef
#
# Run Xia2Log.py
#
# NB Need to set the XIA2HTMLDIR to the location of the
# Xia2Log.py script
#
# CVS_id $Id: xia2html,v 1.2 2009/11/16 13:21:50 pjx Exp $
#
# Set up the environment
export XIA2HTMLDIR=$XIA2_ROOT/Modules/Xia2html
# Run the Xia2log.py script
python $XIA2HTMLDIR/Xia2html.py ${1+"$@"}
#
# Start Firefox to show the file.
##exec firefox xia2.html
