XDSFiles = [
    "X-CORRECTIONS.cbf",
    "Y-CORRECTIONS.cbf",
    "BKGINIT.cbf",
    "BLANK.cbf",
    "GAIN.cbf",
    "BKGPIX.cbf",
    "ABS.cbf",
    "FRAME.cbf",
    "DX-CORRECTIONS.cbf",
    "DY-CORRECTIONS.cbf",
    "GX-CORRECTIONS.cbf",
    "GY-CORRECTIONS.cbf",
    "ABSORP.cbf",
    "DECAY.cbf",
    "MODPIX.cbf",
]
