# This workflow will check pull requests for merge conflicts and
# automatically add (and remove) a relevant label

name: identify merge conflicts
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolved
  pull_request:
    types: [synchronize]

jobs:
  label:
    runs-on: ubuntu-20.04

    steps:
    - name: Label Conflicting Pull Requests
      uses: eps1lon/actions-label-merge-conflict@b8bf8341285ec9a4567d4318ba474fee998a6919
            # This is tagged version v2.0.1, but do not use version tags
            # https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
      with:
        dirtyLabel: "PR: merge conflicts"
        removeOnDirtyLabel: "PR: ready to ship"
        repoToken: ${{ secrets.GITHUB_TOKEN }}
