# This workflow will check pull requests for merge conflicts and
# automatically add (and remove) a relevant label

name: identify merge conflicts
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolved
  pull_request:
    types: [synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Label Conflicting Pull Requests
      uses: eps1lon/actions-label-merge-conflict@1b1b1fcde06a9b3d089f3464c96417961dde1168
      with:
        dirtyLabel: 'PR: merge conflicts'
        repoToken: ${{ secrets.GITHUB_TOKEN }}
